### ISSUE TITLE
Question about the source code for the generation pipeline and the resources for textures and models

### ISSUE THREAD

**Issue by guyleaf** [larics/synthetic-UAV#3]
Hi, thank you for making this great work!

I'm creating a UAV dataset for challenging weather conditions, and I'd love to build upon your work.

I was wondering if you could share the resources for the textures and models and, if possible, the source code for the pipeline.
It would be beneficial for my project.

Thanks

**Comment by antonellabarisic** [comment]
Hi, thank you for your interest in our work! Unfortunately, we are unable to share the assets and source code due to the commercialization of our research results. However, we are open to research or industry collaborations if that’s something you’d be interested in. Feel free to reach out to me directly at antonella.barisic@fer.hr

The methodology is thoroughly described in the paper, and any publicly available resources are linked within. If you need a copy of the paper, I’d be happy to send you the PDF.

**Comment by guyleaf** [comment]
I see, thanks for reply!

By the way, just in case.
Could I use your UAV model, kopterworx, as one of UAV models in my synthetic dataset for research with citing this paper?
I found the model in your personal repository, [here](https://github.com/antonellabarisic/px4_gazebo/tree/master/models/kopterworx).
I think it is also the custom one mentioned in this paper.

**Comment by antonellabarisic** [comment]
Yes, that's our custom model "Eagle/kopterworx" from the paper. You’re welcome to use it! If you do, we would appreciate citing our work in your project. Thanks, and best of luck with your project!
